---
downloads: ~/.ansible-downloads/

configure_sudoers: no

dotfiles_repo: https://github.com/DonPwrShellHunt/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Code/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - gdbm
  - git
  - hugo
  - node
  - python
  - sqlite
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/versions
  - homebrew/binary
  - homebrew/completion
  # - homebrew/php
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - docker
  # - dropbox
  # - fing
  # - firefox
  - google-chrome
  # - handbrake
  # - hipchat
  - iterm2-beta
  # - java
  - kdiff3
  # - licecap
  # - limechat
  # - macvim
  # - menumeters
  # - yujitach-menumeters # Forked version for 10.11+ support.
  # - nvalt
  # - sequel-pro
  # - skype
  # - skitch
  # - slack
  # - sublime-text
  # - transmit
  # - vagrant
  # - virtualbox
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids: []
mas_email: ""
mas_password: ""
