---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"  # better method to reference optional config.yml
      tags: ['always']

    - name: show confirmation of correct placement of config.yml
      debug:
        msg: "config.yml is in playbook directory? {{ config_visible | default('Guess NOT') }}"
      tags:
        - test

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

  tasks:
    - include: tasks/ansible-setup.yml

    - include: tasks/sudoers.yml
      when: configure_sudoers

    - include: tasks/terminal.yml
      when: configure_terminal

    - include: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - include: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
