---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml  # relative path defaults to ./files, so ../config.yml is in main.yml directory
      tags:
        - test

    - name: show confirmation of correct placement of config.yml
      debug:
        msg: "config.yml is in main.yml directory? {{ config_visible | default('Guess NOT') }}"
      tags:
        - test

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
    - name: geerlingguy.mas
      when: mas_installed_app_ids

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/preferences.yml

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    - name: Run .osx dotfiles, update when clause once I understand .osx usage
      shell: ~/.osx --no-restart
      changed_when: false
      when: false
